### ISSUE TITLE
Versions don't serialize/deserialize as expected

### ISSUE THREAD

**Issue by russellbanks** [fosskers/rs-versions#21]
I would expect Versioning and others to serialize and deserialize as their string representations. However, this is not the case. Here's an example using serde_yaml:
```rust
#[derive(Serialize)]
struct Data {
    version: Versioning,
}

println!(
    "{}",
    serde_yaml::to_string(&Data {
        version: Versioning::new("1.2.3").unwrap()
    })?
);
```

Actual:

```yaml
version: !Ideal
  major: 1
  minor: 2
  patch: 3
  pre_rel: null
  meta: null
```

Expected:

```yaml
version: 1.2.3
```

Deserializing the expected result above results in this error:
```
unknown variant `1.2.3`, expected one of `Ideal`, `General`, `Complex`
```

Custom implementations of serialize and deserialize may be needed in this library instead of deriving them.

**Comment by fosskers** [comment]
This has definitely crossed my mind before. The question is, what does the user expect? This obviously depends on the scenario. Cases could be made for (de)serializing in either style. 

I'm interested in providing this functionality, so let's discuss how we could do that.

**Comment by russellbanks** [comment]
I can't imagine a scenario where a user would want the format above, especially for Versioning, as the output will vary entirely based on what the version was parsed as (semver, mess, etc). For example, serializing `abcd` as a Versioning has a completely different result to the above despite it being the same struct:
```yaml
version: !General
  epoch: null
  chunks:
  - !Alphanum abcd
  release: null
  meta: null
```

The only consistent format between any version type is a plain string representation - what the display implementation does.

Serialize and Deserialize can be implemented manually rather than derived and Serde has [documentation](https://serde.rs/custom-serialization.html) on this. Implementing serialize should be pretty easy as to_string just needs to be called. I haven't tested it but something like this:

```rust
impl Serialize for Versioning {
    fn serialize<S>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error> where S: Serializer {
        serializer.serialize_str(&self.to_string())
    }
}
```

Deserialization looks like it takes a [bit more to implement](https://serde.rs/impl-deserialize.html) but that shouldn't be too difficult to do.

**Comment by fosskers** [comment]
I've written manual implementations before so that's not what I'm worried about, but the question is whether or not we want to break the API by making this change, or if we want to make it some other way.

Actually, would it break the API? Only if someone had been using the auto-derived impls and then manipulating them as JSON objects in some other language, instead of just sending them to some other Rust process. Perhaps not the end of the world. One could also argue it's not an API break and instead a fix.

**Comment by fosskers** [comment]
And given that you're the first person to report this, I think it's reasonable perhaps that we do alter the instances as you're suggesting.

**Comment by elenakrittik** [comment]
> My opinion is that this would be a fix. Whilst it would technically be an API break, I can't imagine anyone relying on this behaviour as it was not what I would have expected the version to serialize as.

Imagine me then 😄

Contrary to OP, i consider this behaviour to be expected. Since we're serialising a struct, the serialised string should represent that struct, not what the struct itself represents. If i wanted something like

> Expected:
> 
> ```yaml
> version: 1.2.3
> ```

Then i'd write `format!("version: {}", version.to_string())`, or write version to file as-is if it's the only data i want to store.

**Comment by russellbanks** [comment]
> Contrary to OP, i consider this behaviour to be expected. Since we're serialising a struct, the serialised string should represent that struct, not what the struct itself represents.

Usually serde structs follow some kind of schema, like a JSON schema when using an API, etc. Versioning specifically will never be able to follow a schema because it's output will be different dependening on what kind of version it is.

**Comment by fosskers** [comment]
@elenakrittik Do you rely on the current behaviour?

**Comment by elenakrittik** [comment]
> @elenakrittik Do you rely on the current behaviour? None of the released crates that depend on this library seem to: [lib.rs/crates/versions/rev](https://lib.rs/crates/versions/rev)

No, i currently don't. I only thrown an opinion into the discussion.

**Comment by fosskers** [comment]
I've realized a reason why the serialization needs to stay the way it is, and not be "pretty printed": round-trips / isomorphism. It would otherwise be possible, for example, to construct by hand a `Version` whose pretty form were `1.2.3`, which upon subsequent deserialization would deserialize as a `SemVer`. This strikes me as unwanted behaviour, hence I think the auto-derived `impl`s should remain.

**Comment by russellbanks** [comment]
I've worked around this by using a newtype wrapper and implementing Serialize and Deserialize on that rather than using the Serde feature flag. If anyone finds this issue with the same problem, here are the implementations:

```rust
impl Serialize for PackageVersion {
    fn serialize<S>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.0.to_string())
    }
}
```
```rust
impl<'de> Deserialize<'de> for PackageVersion {
    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        String::deserialize(deserializer)?
            .parse()
            .map_err(de::Error::custom)
    }
}
```

**Comment by russellbanks** [comment]
@fosskers as there's a `Versioning::deserialize_pretty` in 6.1.0, could we also get the same for serializing? I would assume this would mean that rather than a newtype wrapper, I could just use `#[serde(with = "Versioning::pretty")]` or both `#[serde(deserialize_with = "Versioning::deserialize_pretty")]` and `#[serde(serialize_with = "Versioning::serialize_pretty")]`.

**Comment by fosskers** [comment]
That's reasonable.
